version: '3.7'

services:
    f-fts:
        container_name: ${CONTAINER}
        image: ${IMAGE}
        build:
            context: .
            dockerfile: Dockerfile
            args:
                HOME: ${DSHOME}
        volumes:
        - '${APP}:${DSHOME}'
        - '${DATA}:${DSDATA}'
        ports:
        - '0.0.0.0:8888:8888'
        command: jupyter-lab --ip 0.0.0.0 --no-browser --allow-root
